name: 'nuget-license-check-action'
description: 'check licenses of nuget packages'
inputs:
  projectDir:
    description: 'Directory with .sln file to check'
    default: '.'
    required: true
  solutionFileName:
    description: 'Filename of the .sln file to check (e.g. sample.sln)'
    default: '.'
    required: true
  allowedLicenses:
    description: 'Allowed licenses as SPDX list e.g. MIT;Apache-2.0'
    required: false
  excludeProjects:
    description: 'List of project patterns to skip, also support wildcard e.g. *Test.csproj;*Xunit.csproj'
    required: false
  toolVersion:
    description: 'Specify version for dotnet tool nuget-license'
    required: false
  exportDir:
    description: 'Directory where licenses.html should be exported to'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
