name: test
on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: check license
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          7.0.x
    - run: dotnet restore sample/Sample.sln
    - run: yarn install --frozen-lockfile
    - name: license-check-action with valid
      uses: ./
      with:
        projectDir: ./sample
        solutionFileName: Sample.sln
        allowedLicenses: MIT;Apache-2.0;BSD-3-Clause;MS-PL
    - name: license-check-action with invalid
      id: license_invalid
      uses: ./
      with:
        projectDir: ./sample
        solutionFileName: Sample.sln
        allowedLicenses: NONE
      continue-on-error: true
    - name: license-check-action with invalid did not fail
      if: steps.license_invalid.outcome != 'failure'
      run: exit 1
